# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grSim_RobotStatus.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='grSim_RobotStatus.proto',
  package='',
  serialized_pb=_b('\n\x17grSim_RobotStatus.proto\"\x85\x01\n\x12grSim_Robot_Status\x12\n\n\x02id\x18\x01 \x02(\r\x12\x14\n\x0cisteamyellow\x18\x02 \x02(\x08\x12\x11\n\trobottype\x18\x03 \x02(\t\x12\x14\n\x0ctouchingball\x18\x04 \x02(\x08\x12\x11\n\tpowerison\x18\x05 \x02(\x08\x12\x11\n\ttimestamp\x18\x65 \x02(\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GRSIM_ROBOT_STATUS = _descriptor.Descriptor(
  name='grSim_Robot_Status',
  full_name='grSim_Robot_Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='grSim_Robot_Status.id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='isteamyellow', full_name='grSim_Robot_Status.isteamyellow', index=1,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='robottype', full_name='grSim_Robot_Status.robottype', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='touchingball', full_name='grSim_Robot_Status.touchingball', index=3,
      number=4, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='powerison', full_name='grSim_Robot_Status.powerison', index=4,
      number=5, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='grSim_Robot_Status.timestamp', index=5,
      number=101, type=1, cpp_type=5, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=161,
)

DESCRIPTOR.message_types_by_name['grSim_Robot_Status'] = _GRSIM_ROBOT_STATUS

grSim_Robot_Status = _reflection.GeneratedProtocolMessageType('grSim_Robot_Status', (_message.Message,), dict(
  DESCRIPTOR = _GRSIM_ROBOT_STATUS,
  __module__ = 'grSim_RobotStatus_pb2'
  # @@protoc_insertion_point(class_scope:grSim_Robot_Status)
  ))
_sym_db.RegisterMessage(grSim_Robot_Status)


# @@protoc_insertion_point(module_scope)
