#!/usr/bin/env python

import sys
from IPython.terminal import embed; ipshell=embed.InteractiveShellEmbed(config=embed.load_default_config())(local_ns=locals())

from rqt_gui.main import Main

main = Main()
sys.exit(main.main(sys.argv, standalone='behavior_tree_visualizer.btv.BTV'))
